name: Build and Deploy code
on:
  push:
    branches:
      - "main"
      - "feat1_branch"
  pull_request:
    branches:
      - "test_branch"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to cnemri
        run: echo "hi cnemri"